# Schema for the configuration files of the Unicana Redirect module.

# This schema tells the config system how to read our config YML files.

unicana_redirect.redirect.*:
  type: mapping
  label: 'Redirect'
  mapping:
    id:
      type: string
      label: 'Redirect id'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Domain'
    replacement_pattern:
      type: string
      label: 'Affiliate Extension'
    type_of_the_pattern:
      type: string
      label: 'Type of the pattern'
    langcode:
      type: string
      label: 'Default language'
