varnish_flush_cron: null
varnish_version: '3'
varnish_control_terminal: '127.0.0.1:6082'
varnish_control_key: e921e030-84b6-47a5-b56d-c38a54a3dd1b
varnish_socket_timeout: '100'
varnish_cache_clear: '1'
varnish_bantype: '0'
varnish_cmdlength_limit: 7500
_core:
  default_config_hash: DxeHlEyOM-znvcRf6mmkhXwywgcKl2f-tvbALo_EtcE
