varnish_flush_cron: null
varnish_version: '3'
varnish_control_terminal: '127.0.0.1:6082'
varnish_control_key: 8312cc98-29c9-400b-805d-0ad0f977e30d
varnish_socket_timeout: '100'
varnish_cache_clear: '1'
varnish_bantype: '0'
varnish_cmdlength_limit: 7500
_core:
  default_config_hash: DxeHlEyOM-znvcRf6mmkhXwywgcKl2f-tvbALo_EtcE
